import type { Branch, MenuItem } from './types';
import branchesData from '@/config/branches.json';

export const branches: Branch[] = branchesData.branches;

export const menuItems: MenuItem[] = [
  {
    id: 'deal-1',
    name: 'Somewhat Amazing 1',
    description: '2 Bazinga burgers, Reg. fries, 2 reg. drinks',
    price: 1250,
    category: 'Deals',
    imageId: 'deal-1',
  },
  {
    id: 'deal-2',
    name: 'Somewhat Amazing 2',
    description: '2 Bazinga burgers, 2 pcs chicken, Large fries, 2 reg. drinks',
    price: 1750,
    category: 'Deals',
    imageId: 'deal-2',
  },
  {
    id: 'deal-3',
    name: 'Somewhat Amazing 3',
    description: '3 Bazinga burgers, Large fries, 1 liter drink',
    price: 1890,
    category: 'Deals',
    imageId: 'deal-3',
  },
  {
    id: 'deal-4',
    name: 'Somewhat Amazing 4',
    description: '3 Bazinga burgers, 3 pcs chicken, 1 liter drink',
    price: 2150,
    category: 'Deals',
    imageId: 'deal-4',
  },
  {
    id: 'p-small',
    name: 'Small Pizza',
    description: '6" small pizza with 1 reg. Drink (345 ml)',
    price: 750,
    category: 'Pizzas',
    imageId: 'pizza-small',
  },
  {
    id: 'p-reg',
    name: 'Regular Pizza',
    description: '9" regular pizza with 2 reg. Drinks (345 ml)',
    price: 1450,
    category: 'Pizzas',
    imageId: 'pizza-regular',
  },
  {
    id: 'p-large',
    name: 'Large Pizza',
    description: '12" large pizza with 1 liter drink',
    price: 1990,
    category: 'Pizzas',
    imageId: 'pizza-large',
  },
  {
    id: 'b1',
    name: 'The Cheezious Classic',
    description: 'Our signature beef burger with special sauce, lettuce, cheese, pickles, onions on a sesame seed bun.',
    price: 8.99,
    category: 'Burgers',
    imageId: 'burger-1',
  },
  {
    id: 'b2',
    name: 'Zesty Chicken Burger',
    description: 'Crispy chicken fillet with a zesty mayo, lettuce, and tomato.',
    price: 7.99,
    category: 'Burgers',
    imageId: 'burger-2',
  },
  {
    id: 's1',
    name: 'Golden Fries',
    description: 'Perfectly crispy and salted french fries.',
    price: 3.49,
    category: 'Sides',
    imageId: 'side-1',
  },
  {
    id: 'd1',
    name: 'Soft Drink (Regular)',
    description: 'Regular size soft drink.',
    price: 100,
    category: 'Drinks',
    imageId: 'drink-1',
  },
  {
    id: 'd2',
    name: 'Soft Drink (1 Liter)',
    description: '1 liter soft drink bottle.',
    price: 190,
    category: 'Drinks',
    imageId: 'drink-liter',
  },
  {
    id: 'd3',
    name: 'Soft Drink (1.5 Liter)',
    description: '1.5 liter soft drink bottle.',
    price: 220,
    category: 'Drinks',
    imageId: 'drink-liter',
  },
  {
    id: 'd4',
    name: 'Water (Small Bottle)',
    description: 'Small bottle of mineral water.',
    price: 60,
    category: 'Drinks',
    imageId: 'drink-2',
  },
  {
    id: 'd5',
    name: 'Small Juice',
    description: 'A small carton of juice.',
    price: 60,
    category: 'Drinks',
    imageId: 'juice-small',
  },
];
